"""create_artworks_table

Revision ID: 4e50453d5dce
Revises: ddb345c4a75e
Create Date: 2026-03-07 20:31:47.688048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e50453d5dce'
down_revision: Union[str, Sequence[str], None] = 'ddb345c4a75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), server_default='Untitled', nullable=False),
    sa.Column('source_image_url', sa.String(length=255), nullable=False),
    sa.Column('result_image_url', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hall_published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("visibility in ('private','profile','hall','hidden')", name='ck_artworks_visibility'),
    sa.CheckConstraint('comment_count >= 0', name='ck_artworks_comment_count'),
    sa.CheckConstraint('download_count >= 0', name='ck_artworks_download_count'),
    sa.CheckConstraint('like_count >= 0', name='ck_artworks_like_count'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artworks_author_id'), 'artworks', ['author_id'], unique=False)
    op.create_index(op.f('ix_artworks_style_id'), 'artworks', ['style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artworks_style_id'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_author_id'), table_name='artworks')
    op.drop_table('artworks')
    # ### end Alembic commands ###
