"""create_generation_tasks_table

Revision ID: ab0590cfd6fe
Revises: 3263571fb88c
Create Date: 2026-03-07 21:11:04.149764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0590cfd6fe'
down_revision: Union[str, Sequence[str], None] = '3263571fb88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('input_image_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error_msg', sa.String(length=255), nullable=True),
    sa.Column('output_artwork_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('pending','running','success','failed')", name='ck_generation_tasks_status'),
    sa.ForeignKeyConstraint(['output_artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_style_id'), 'generation_tasks', ['style_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_user_id'), 'generation_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_tasks_user_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_style_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    # ### end Alembic commands ###
